name: fill_gallon
description: A sample command-line application for the Yes List Fill Gallon library.
version: 1.0.0
homepage: https://github.com/marcelomfranca/yeslist_fill_gallon/tree/main/examples/fill_gallon

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  yeslist_fill_gallon:
    path: ../../
#  path: ^1.7.0

dev_dependencies:
  #pedantic: ^1.9.0
  test: ^1.14.4
